root: true

parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  ecmaVersion: 2020,
  extraFileExtensions: [".svelte"]

plugins:
  - "@typescript-eslint"
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:svelte/recommended"
  - "prettier"

overrides:
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
